services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3010:3000"
    env_file:
      - .env
    volumes:
      - .:/app
      - /app/node_modules
    restart: unless-stopped